# -*- coding: utf-8 -*-
"""Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f2_7yWtRAIWiA_ddorJmAQJVbCz9_OZz

# Python

---

## Seu primeiro programa 🐣
"""

nome = input("Qual é o seu nome? ")
print(f"Hello {nome}")

"""1. Faça um Programa que mostre a mensagem "Alo mundo" na tela.
2. Faça um Programa que peça um número e então mostre a mensagem "O número informado foi [número]."
3. Faça um Programa que peça dois números e imprima a soma.
4. Faça um Programa que peça as 3 notas e mostre a média.
5. Faça um Programa que converta metros para centímetros.
"""

print("Alo mundo")

numero = input("Digite um número: ")
print(f"O número informado foi {numero}")

"""## Operadores
### Aritméticos:
![alt text](https://image.slidesharecdn.com/introduoapython-iijtims-mdulo1-131108230122-phpapp01/95/introduo-python-mdulo-1-46-638.jpg?cb=1383951826)
### Lógicos:
![alt text](https://image.slidesharecdn.com/apresentao-170510192311/95/captulo-2-python-6-638.jpg?cb=1494444228)
"""

# SOMA
1+1

# SUBTRAÇÃO
1-1

# MULTIPLICAÇÃO
1*10

# DIVISÃO
100 / 3

# EXPONENCIAÇÃO
4**2

"""## Tipos de Dados

---

* Inteiros:  declarados com **int()**
<br>
Exemplo de inteiros: 4, -234455, 21543...
<br><br>
* Flutuantes:  conhecidos como floating, são números decimais, declarados com **float()**
<br>
Exemplo de flutuantes: 4.0, -23.5, 215.43
<br><br>
* Booleanos:  conhecidos como lógicos, temos "True" ou "False", declarados com **bool()**
<br>
Exemplo de booleanos: True, False
<br><br>
* Strings:  conhecidos como cadeia de caracteres, inseridos entre aspas(duplas ou simples), declarados com **str()**
<br>
Exemplo de strings: "oi!", "27", "23.50"
"""

inteiro = 12
type(inteiro)

flutuante = 12.5
type(flutuante)

booleano = True
type(booleano)

caracter = "Olá, mundo!"
type(caracter)

# VOCÊ PODE ALTERAR ALGUNS TIPOS DE DADOS
10.45 - "joão"

"""## Estruturas de Dados"""

# LISTA
lista1 = []
lista2 = ['josé', 'maria']
lista3 = ['oi', 3.0, 40, True]

dir(lista1)

lista1.insert(0, "olá")
lista1

# TUPLAS
tup = (1,2,3)
#dir(tup)
tup.count(4)

# SETS
set1 = ({1,2,3})
set2 = set([1,2,3])
dir(set1)
set1.pop()

# DICIONARIOS
pessoas = {
    "name": "joao",
    "age": 39, 
    "skills": ['python', 'r', 'java']
}
pessoas.values()

"""## Condicionais"""

# IF
if 100 > 99:
  print("100 é maior que 99!")

# IF, ELSE
if 100 == 99:
  print("100 e 99 são iguais!")
else:
  print("100 é diferente de 99")

# IF, ELIF, ELSE
if 100 == 99:
  print("100 e 99 são iguais!")
elif 100 > 99:
  print("100 é maior que 99!")
else:
  print("100 é menor que 99!")

"""6. Faça um Programa que peça dois números e imprima o maior deles.
7. Faça um Programa que peça um valor e mostre na tela se o valor é positivo ou negativo.
8. Faça um Programa que verifique se uma letra digitada é "F" ou "M". Conforme a letra escrever: F - Feminino, M - Masculino, Sexo Inválido.
9. Faça um Programa que verifique se uma letra digitada é vogal ou consoante.
10. Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e apresentar:
* A mensagem "Aprovado", se a média alcançada for maior ou igual a sete;
* A mensagem "Reprovado", se a média for menor do que sete;
* A mensagem "Aprovado com Distinção", se a média for igual a dez.
"""

num1 = int(input(""))

if num1 > 0:
  print("O número é positivo!")
else:
  print("O número é negativo")

"""## Repetição"""

# FOR range
for x in range(0,18,3):
  print(x)

# FOR
palavra = "PALAVRA"
for letra in palavra:
  print(letra)

# WHILE
num = 0
while True:
  print(num)
  num   = num + 1

"""11. Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
12. Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.
13. Faça um programa que leia e valide as seguintes informações:
* Nome: maior que 3 caracteres;
* Idade: entre 0 e 150;
* Salário: maior que zero;
* Sexo: 'f' ou 'm';
* Estado Civil: 's', 'c', 'v', 'd';
14. Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento.
15. Altere o programa anterior permitindo ao usuário informar as populações e as taxas de crescimento iniciais. Valide a entrada e permita repetir a operação.
"""

num1 = int(input("Digite um valor entre 0 e 10: "))
while num1 < 0 or num1 > 10:
  print("Valor inválido!")
  num1 = int(input("Digite um valor entre 0 e 10: "))

"""## Funções"""

def RaizQuadrada(x,y):
  return x**y

RaizQuadrada(2,2)

def Maiuscula(x):
  return x.upper()

Maiuscula("oi")

"""16. Faça um programa, com uma função que necessite de três argumentos, e que forneça a soma desses três argumentos.
17. Faça um programa, com uma função que necessite de um argumento. A função retorna o valor de caractere ‘P’, se seu argumento for positivo, e ‘N’, se seu argumento for zero ou negativo.
18. Faça um programa com uma função chamada somaImposto. A função possui dois parâmetros formais: taxaImposto, que é a quantia de imposto sobre vendas expressa em porcentagem e custo, que é o custo de um item antes do imposto. A função “altera” o valor de custo para incluir o imposto sobre vendas.
"""

def Func(a,b,c):
  return a+b+c 

Func(-12,-134,128)

"""# JOGO DA FORCA!"""

import random

def get_word():
    lista_palavras = ['gata', 'cão', 'lagarto', 'centopéia', 'boi']
    word = random.choice(lista_palavras)
    return word.upper()

def play(word):
    word_completion = "_" * len(word) 
    guessed = False
    guessed_letters = []
    guessed_words = []
    tries = 6
    print(f"JOGO DA FORCA!\nDica: {len(word)} letras!")
    print(display_hangman(tries))
    print(word_completion)
    print("\n")
    
    while not guessed and tries > 0:
        guess = input("Adivinhe uma letra ou palavra: ").upper()
        if len(guess) == 1 and guess.isalpha():
            if guess in guessed_letters:
                print("Você já tentou ", guess)
            elif guess not in word:
                print(guess, "Não.")
                tries -= 1
                guessed_letters.append(guess)
            else:
                print(guess, "está na palavra!")
                guessed_letters.append(guess)
                word_as_list = list(word_completion)
                indices = [i for i, letter in enumerate(word) if letter == guess]
                for index in indices:
                    word_as_list[index] = guess
                word_completion = "".join(word_as_list)
                if "_" not in word_completion:
                    guessed = True
        elif len(guess) == len(word) and guess.isalpha():
            if guess in guessed_words:
                print("Você já tentou a palavra", guess)
            elif guess != word:
                print(guess, "não é a palavra.")
                tries -= 1
                guessed_words.append(guess)
            else:
                guessed = True
                word_completion = word
        else:
            print("Inválido.")
        print(display_hangman(tries))
        print(word_completion)
        print("\n")
    if guessed:
        print("Parabéns, você adivinhou a palavra! Você venceu!")
    else:
        print("Você perdeu!. A palavra era " + word + ".")

def display_hangman(tries):
    stages = [  # cabeça, tronco e braços e pernas: morte.
                """
                   --------
                   |      |
                   |      O
                   |     \|/
                   |      |
                   |     / \
                   -
                """,
                # cabeça, tronco e braços, perna
                """
                   --------
                   |      |
                   |      O
                   |     \|/
                   |      |
                   |     / 
                   -
                """,
                # cabeça, tronco e braços
                """
                   --------
                   |      |
                   |      O
                   |     \|/
                   |      |
                   |      
                   -
                """,
                # cabeça, tronco e braço
                """
                   --------
                   |      |
                   |      O
                   |     \|
                   |      |
                   |     
                   -
                """,
                # cabeça e tronco
                """
                   --------
                   |      |
                   |      O
                   |      |
                   |      |
                   |     
                   -
                """,
                # cabeça
                """
                   --------
                   |      |
                   |      O
                   |    
                   |      
                   |     
                   -
                """,
                # vazio
                """
                   --------
                   |      |
                   |      
                   |    
                   |      
                   |     
                   -
                """
    ]
    return stages[tries]

def main():
    word = get_word()
    play(word)
    while input("Jogar de novo? (S/N) ").upper() == "S":
        word = get_word()
        play(word)


if __name__ == "__main__":
    main()

"""# CHATBOT

---
https://chatterbot.readthedocs.io/en/stable/
"""

!pip install chatterbot
!pip install chatterbot_corpus

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.trainers import ChatterBotCorpusTrainer

bot = ChatBot('Pybot')
bot = ChatBot(
    'Pybot',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    database_uri='sqlite:///database.sqlite3'
    )
    
conversa = ListTrainer(bot)
conversa.train([
    'Oi?',
    'Olá',
    'Qual o seu nome?',
    'Pybot',
    'Prazer em te conhecer',
    'Igualmente!',
    'Tudo bem?',
    'Muito bem e você?',
    'Ótimo',
    'Papo bom o nosso',
    'kkk',
    'adeus',
    'Volte sempre!',
])

trainer = ChatterBotCorpusTrainer(bot)
trainer.train('chatterbot.corpus.portuguese')

while True:
  resposta = bot.get_response(input("Usuário: "))
  if float(resposta.confidence) > 0.5:
      print("Irineu: ", resposta)
  else:
      print("Desculpe, eu não entendi!")